version: "2.1"
services:

  db:
    image: postgres
    container_name: soaDB
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=soaDB
    command: postgres -p 5432
    ports:
      - "5432:5432"

  consul:
    image: consul:latest
    container_name: consul
    ports:
      - "8500:8500"

  basic:
    image: basic
    container_name: basic
    depends_on:
      - db
      - consul
    environment:
      - APPLICATION_NAME=basic
      - APPLICATION_PORT=8080
      - DATABASE_HOST=soaDB
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=soaDB
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    ports:
      - "8080:8080"

  eureka:
    image: eureka
    container_name: eureka
    environment:
      - APPLICATION_NAME=eureka-server
      - APPLICATION_PORT=8761
      - CONFIG_URL=http://config:8095
    ports:
      - "8761:8761"

  additional:
    image:  additional
    container_name: additional
    depends_on:
      - config
      - eureka
      - basic
    environment:
      - APPLICATION_NAME=additional
      - APPLICATION_PORT=8081
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - EUREKA_SERVER=http://eureka:8761/eureka/
      - RIBBON_NAME=client
      - CONFIG_URL=http://config:8095
    ports:
      - "8081:8081"

  gateway:
    image: gateway
    container_name: gateway
    environment:
      - APPLICATION_NAME=service-gateway
      - APPLICATION_PORT=9912
      - EUREKA_SERVER=http://eureka:8761/eureka/
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
    ports:
      - "9912:9912"

  config:
    image: config
    container_name: config
    environment:
      - APPLICATION_NAME=config-server
      - APPLICATION_PORT=8095
      - GIT_URL=https://github.com/DeltaHeavyVIP/spring-config
      - GIT_BRANCH=master
    ports:
      - "8095:8095"