server:
  port: 9912

spring:
  application:
    name: service-gateway
  cloud:
    consul:
      discovery:
        enabled: true
      port: 8500
      host: localhost
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
      routes:
        - id: additional
#           имя микросервиса (как зарегестрированно в consul&eureka) куда перенаправляем+ балансировщик
          uri: lb://additional
          predicates:
            - Path=**/ebay/**
#          отброс 1 части URI
#          filters:
#            - StripPrefix=1
#          Порядок обработки маршрута
          order: 0
        - id: basic
          uri: lb://basic
          predicates:
            - Path=/**
          order: 1